services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kdb
      POSTGRES_USER: kadmin
      POSTGRES_PASSWORD: kadmin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    extends:
      file: common.yml
      service: ms-deploy-network
      
  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
      - "7777:27017"
    volumes:
      - mongo_data:/data/db
    extends:
      file: common.yml
      service: ms-deploy-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: kdb
      KC_DB_PASSWORD: kadmin
      KC_DB_USERNAME: kadmin
      KC_DB_SCHEMA: public
    command: "start-dev"
    depends_on:      
      postgres:
        condition: service_healthy
    extends:
      file: common.yml
      service: ms-deploy-network

networks:
  pisethbanknet:

volumes:
  postgres_data:
  mongo_data:
