version: '3.8'

services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "5689:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: host.docker.internal
      ME_CONFIG_MONGODB_PORT: 7777
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
