version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=kdb
      - POSTGRES_PASSWORD=kadmin
      - POSTGRES_DB=kadmin
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
